publish:
  maze-build:
    image: mikkeloscar/maze-build

publish:
  maze-publish:
    image: mikkeloscar/maze-publish
    url: http://publish.moscar.net
    repo: mikkeloscar/maze
    auth_token: $$AUTH_TOKEN
